// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.0.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Sloppy.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Basic options")]
    public partial class BasicOptionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BasicOptions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Basic options", "In order to easily parse input\r\nAs a developer\r\nI want to be sure my argument obj" +
                    "ect returns the proper results", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Long option with no value exists")]
        public virtual void LongOptionWithNoValueExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Long option with no value exists", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table1.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 7
 testRunner.Given("I have the following option", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table2.AddRow(new string[] {
                        "--verbose"});
#line 10
 testRunner.When("I pass in the arguments", ((string)(null)), table2);
#line 13
 testRunner.Then("the property verbose should exist");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Long option with no value returns null")]
        public virtual void LongOptionWithNoValueReturnsNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Long option with no value returns null", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table3.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 17
 testRunner.Given("I have the following option", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table4.AddRow(new string[] {
                        "--verbose"});
#line 20
 testRunner.When("I pass in the arguments", ((string)(null)), table4);
#line 23
 testRunner.Then("the property verbose should return \"<null>\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Short option with no value exists")]
        public virtual void ShortOptionWithNoValueExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Short option with no value exists", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table5.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 26
 testRunner.Given("I have the following option", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table6.AddRow(new string[] {
                        "-v"});
#line 29
 testRunner.When("I pass in the arguments", ((string)(null)), table6);
#line 32
 testRunner.Then("the property verbose should exist");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Short option with no value returns null")]
        public virtual void ShortOptionWithNoValueReturnsNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Short option with no value returns null", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table7.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 36
 testRunner.Given("I have the following option", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table8.AddRow(new string[] {
                        "-v"});
#line 39
 testRunner.When("I pass in the arguments", ((string)(null)), table8);
#line 42
 testRunner.Then("the property verbose should return \"<null>\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Long option with value exists")]
        public virtual void LongOptionWithValueExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Long option with value exists", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table9.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
#line 46
 testRunner.Given("I have the following option", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table10.AddRow(new string[] {
                        "--message"});
            table10.AddRow(new string[] {
                        "bad clown, sad summmer"});
#line 49
 testRunner.When("I pass in the arguments", ((string)(null)), table10);
#line 53
 testRunner.Then("the property message should exist");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Long option with value returns value")]
        public virtual void LongOptionWithValueReturnsValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Long option with value returns value", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table11.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
#line 57
 testRunner.Given("I have the following option", ((string)(null)), table11);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table12.AddRow(new string[] {
                        "--message"});
            table12.AddRow(new string[] {
                        "bad clown, sad summmer"});
#line 60
 testRunner.When("I pass in the arguments", ((string)(null)), table12);
#line 64
 testRunner.Then("the property message should return \"bad clown, sad summmer\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Short option with value exists")]
        public virtual void ShortOptionWithValueExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Short option with value exists", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table13.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
#line 67
 testRunner.Given("I have the following option", ((string)(null)), table13);
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table14.AddRow(new string[] {
                        "-m"});
            table14.AddRow(new string[] {
                        "bad clown, sad summmer"});
#line 70
 testRunner.When("I pass in the arguments", ((string)(null)), table14);
#line 74
 testRunner.Then("the property message should exist");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Short option with value returns value")]
        public virtual void ShortOptionWithValueReturnsValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Short option with value returns value", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table15.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
#line 78
 testRunner.Given("I have the following option", ((string)(null)), table15);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table16.AddRow(new string[] {
                        "-m"});
            table16.AddRow(new string[] {
                        "bad clown, sad summmer"});
#line 81
 testRunner.When("I pass in the arguments", ((string)(null)), table16);
#line 85
 testRunner.Then("the property message should return \"bad clown, sad summmer\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
