// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.0.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Sloppy.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Required params")]
    public partial class RequiredParamsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RequiredParams.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Required params", "In order to ensure the user thinks about some optiosn \r\nAs a developer\r\nI want to" +
                    " be some params are being passed", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("a required option is passed")]
        public virtual void ARequiredOptionIsPassed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("a required option is passed", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table1.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
            table1.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 7
 testRunner.Given("I have the following option that is required", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table2.AddRow(new string[] {
                        "--message"});
            table2.AddRow(new string[] {
                        "bad clown, sad summmer"});
            table2.AddRow(new string[] {
                        "--verbose"});
#line 11
 testRunner.When("I pass in the arguments", ((string)(null)), table2);
#line 16
 testRunner.Then("the property message should return \"bad clown, sad summmer\"");
#line 17
 testRunner.And("the property verbose should exist");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("a required option is not passed")]
        public virtual void ARequiredOptionIsNotPassed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("a required option is not passed", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "short",
                        "long",
                        "description"});
            table3.AddRow(new string[] {
                        "m",
                        "message",
                        "message"});
            table3.AddRow(new string[] {
                        "v",
                        "verbose",
                        "verbose"});
#line 20
 testRunner.Given("I have the following option that is required", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "args"});
            table4.AddRow(new string[] {
                        "--verbose"});
#line 24
 testRunner.When("I pass in the arguments", ((string)(null)), table4);
#line 27
 testRunner.Then("there should be an exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
